/**
 * An EPS writer.
 * @todo make global container of all elements and put them in the right order.
 * @todo detailed error/warning when primitive is not drawn.
 */
var EPS = function(boundingBox) {
    DocumentWriter.apply(this, arguments);

    this.bbox = boundingBox;
    this._doc.header = "%!PS-Adobe-2.0 EPSF-2.0";
    this._doc.footer = "%%EOF";
};
EPS.prototype = Object.create(DocumentWriter.prototype);
EPS.prototype.constructor = EPS;
EPS.prototype.kw = {
    gs: " gsave ",
    gr: " grestore ",
    np: " newpath ",
    lw: " setlinewidth ",
    mt: " moveto ",
    lt: " lineto ",
    c: " setrgbcolor ",
    f: " fill ",
    s: " stroke ",
    a: " arc ",
    cp: " closepath "
};

EPS.prototype._drawLine = function (line) {
    var kw = EPS.prototype.kw;

    var res = kw.gs + kw.np;
    res += line.stroke.r + " " + line.stroke.g + " " + + line.stroke.b + kw.c;
    res += line.strokeWidth + kw.lw;
    res += line.src.x + " " + line.src.y + kw.mt + line.dst.x + " " + line.dst.y + kw.lt + kw.s;
    res += kw.gr + "\n";
    return res;
};

EPS.prototype._drawCircle = function(circle) {
    var kw = EPS.prototype.kw;
    var geometry = circle.pos.x + " " + circle.pos.y + " " + circle.radius + " 0 360" + kw.a;

    var res = kw.gs + kw.np;
    // Fill only
    if (circle.stroke == null) {
        res += circle.fill.r + " " + circle.fill.g + " " + circle.fill.b + kw.c;
        res += geometry;
        res += kw.cp + kw.f;
    } else if (circle.fill == null) {
        // Stroke only
        res += circle.stroke.r + " " + circle.stroke.g + " " + circle.stroke.b + kw.c;
        res += circle.strokeWidth + kw.lw;
        res += geometry;
        res += kw.cp + kw.s;
    } else {
        // Fill + stroke
        res += circle.fill.r + " " + circle.fill.g + " " + circle.fill.b + kw.c;
        res += geometry;
        res += kw.cp;
        res += kw.gs + kw.f + kw.gr;
        res += circle.stroke.r + " " + circle.stroke.g + " " + circle.stroke.b + kw.c;
        res += circle.strokeWidth + kw.lw + kw.s;
    }
    res += kw.gr + "\n";
    return res;
};

EPS.prototype._drawPolygon = function(polygon) {
    var kw = EPS.prototype.kw;

    var res = kw.gs + kw.np;
    var geometry = polygon.corners[0].x + " " + polygon.corners[0].y + kw.mt;
    for (var i = 1; i < polygon.corners.length; i++) {
        geometry += polygon.corners[i].x + " " + polygon.corners[i].y + kw.lt;
    }
    // Fill only
    if (polygon.stroke == null) {
        res += polygon.fill.r + " " + polygon.fill.g + " " + polygon.fill.b + kw.c;
        res += geometry;
        res += kw.cp + kw.f;
    } else if (polygon.fill == null) {
        // Stroke only
        res += polygon.stroke.r + " " + polygon.stroke.g + " " + polygon.stroke.b + kw.c;
        res += geometry;
        res += kw.cp + kw.s;
    } else {
        // FIll + stroke
        res += polygon.fill.r + " " + polygon.fill.g + " " + polygon.fill.b + kw.c;
        res += geometry;
        res += kw.cp;
        res += kw.gs + kw.f + kw.gr;
        res += polygon.stroke.r + " " + polygon.stroke.g + " " + polygon.stroke.b + kw.c;
        res += polygon.strokeWidth + kw.lw + kw.s;
    }
    res += kw.gr + "\n";
    return res;
};

EPS.prototype._drawPath = function (path) {
    var kw = EPS.prototype.kw;

    var res = "\n% Paths\n%\n";
    res += kw.gs + kw.np;
    res += path.stroke.r + " " + path.stroke.g + " " + path.stroke.b + kw.c;
    res += path.strokeWidth + kw.lw + kw.f;
    res += path.segments[0].x + " " + path.segments[0].y + kw.mt;
    for (var i=1; i<path.segments.length; i++) {
        res += path.segments[i].x + " " + path.segments[i].y + kw.lt;
    }
    res += kw.s + kw.gr + "\n";
    return res;
};

EPS.prototype.make = function() {
    // Header
    var doc = this._doc.header + "\n% Generated by " + this._doc.author + "\n";
    doc += "%%BoundingBox: 0 0 " + this.bbox.width + " " + this.bbox.height + "\n";

    // Lines
    doc += "\n% Lines\n%\n";
    this._doc.primitives.lines.forEach(function(l) {
        doc += EPS.prototype._drawLine(l);
    });

    // Circles
    doc += "\n% Circles\n%\n";
    this._doc.primitives.circles.forEach(function(c) {
        doc += EPS.prototype._drawCircle(c);
    });

    // Polygons
    doc += "\n% Polygons\n%\n";
    this._doc.primitives.polygons.forEach(function(p) {
        doc += EPS.prototype._drawPolygon(p);
    });

    // Paths
    doc += "\n% Paths\n%\n";
    this._doc.primitives.paths.forEach(function(p) {
        doc += EPS.prototype._drawPath(p);
    });

    // Footer
    doc += this._doc.footer;

    // Return simplified document
    return doc.replace(/  +/g, " ").replace(/\n /g, "\n");
};
